from sqlalchemy import Integer, String
from typing import Optional
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.orm import MappedAsDataclass, DeclarativeBase


class Base(DeclarativeBase, MappedAsDataclass):
    pass


class ReturnToWorkFromTests(Base):
    __tablename__ = 'return_to_work_from_tests'

    queue: Mapped[str] = mapped_column(String)
    priority: Mapped[str] = mapped_column(String)
    type: Mapped[str] = mapped_column(String)
    key: Mapped[str] = mapped_column(String, primary_key=True)
    summary: Mapped[str] = mapped_column(String)
    assignee: Mapped[str] = mapped_column(String)
    status: Mapped[str] = mapped_column(String)
    returns_to_work: Mapped[int] = mapped_column(Integer)


class ReturnToWorkFromReview(Base):
    __tablename__ = 'return_to_work_from_review'

    queue: Mapped[str] = mapped_column(String)
    priority: Mapped[str] = mapped_column(String)
    type: Mapped[str] = mapped_column(String)
    key: Mapped[str] = mapped_column(String, primary_key=True)
    summary: Mapped[str] = mapped_column(String)
    assignee: Mapped[str] = mapped_column(String)
    status: Mapped[str] = mapped_column(String)
    returns_to_work_from_design_review: Mapped[int] = mapped_column(Integer)


class DevDuration(Base):
    __tablename__ = 'dev_duration'

    queue: Mapped[str] = mapped_column(String)
    priority: Mapped[str] = mapped_column(String)
    type: Mapped[str] = mapped_column(String)
    key: Mapped[str] = mapped_column(String, primary_key=True)
    summary: Mapped[str] = mapped_column(String)
    assignee: Mapped[str] = mapped_column(String)
    status: Mapped[str] = mapped_column(String)
    start_date: Mapped[str] = mapped_column(String)
    end_date: Mapped[str] = mapped_column(String)
    duration: Mapped[str] = mapped_column(String)
    parent_tag: Mapped[str] = mapped_column(String)

class Issues1(Base):
    __tablename__ = 'issues1'
    id: Mapped[Optional[str]] = mapped_column(String, primary_key=True)
    MRIntoDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    MRIntoMaster: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_zakryta: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_cancelled: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_obrabotka: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_protestirovanoNaDevCustom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_testing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_zablokirovana: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_dizajnrevju: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closedDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closed: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_novaja: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inProgress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_proverkaPostanovsikom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_beklog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_tehniceskijProekt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_oceredNaQa: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_backlog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closedProd: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    assignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    boards: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    components: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    deadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    description: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    favorite: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    followers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    key: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    link: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    pendingReplyFrom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    primaryKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    project: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    priority: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    qaEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    queue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    stand: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    start: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusStartTime: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusType: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    status: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    summary: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    tags: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    typeOf: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    version: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    Team: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithoutExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastCommentUpdatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    originalEstimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    estimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatusLastAssignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolution: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    spent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    storyPoints: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    votes: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    access: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    aliases: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bitrixTicketID: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockReason: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bugstage: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistDone: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistItems: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistTotal: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developmentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    emailTo: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    end: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendEnd: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendStart: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Frontend: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    receivedReplyFor: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    regress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    release: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheDesignReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheTesting: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Size: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    sla: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    userEmail: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

class Issues2(Base):
    __tablename__ = 'issues2'
    id: Mapped[Optional[str]] = mapped_column(String, primary_key=True)
    MRIntoDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    MRIntoMaster: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    dur_onHold: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_transferredtothedevelopers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_zakryta: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_thebugislocalized: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_zhdetreliz: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_testing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closedDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closed: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inProgress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_checkforProduction: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_needsProcessing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_dubl: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_otklonen: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_bagpodtverzhden: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_backlog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_new: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    assignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    boards: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bugstage: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    components: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    deadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    description: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    emailTo: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    favorite: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    followers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    key: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    link: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    pendingReplyFrom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    project: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    priority: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    qaEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    queue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    regress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    reporter: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    start: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusStartTime: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusType: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    status: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    summary: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    tags: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    typeOf: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    userEmail: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    version: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    Team: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Size: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    access: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    aliases: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bitrixTicketID: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockReason: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistDone: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistItems: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistTotal: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithoutExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developmentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    end: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    estimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendEnd: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendStart: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Frontend: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastCommentUpdatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_reporter: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    originalEstimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    primaryKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatusLastAssignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    receivedReplyFor: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    release: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolution: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheDesignReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheTesting: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    sla: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    spent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    stand: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    storyPoints: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    unique: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    votes: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

class Issues3(Base):
    __tablename__ = 'issues3'

    id: Mapped[Optional[str]] = mapped_column(String, primary_key=True)
    MRIntoDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    MRIntoMaster: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    dur_zakryta: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_otmenena: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_novaja: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_bagpodtverzhden: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_gotovokrazrabotke: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_transferredtothedevelopers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_acceptance: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inProgress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_vrazrabotke: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_backlog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_dizajn: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_tpRndPoc: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_estNaDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_otklonen: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_new: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_testing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_testplan: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_tpVRabote: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_needsProcessing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_needsTZ: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    assignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    boards: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    components: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    deadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    description: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    favorite: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    followers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    key: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    link: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    pendingReplyFrom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    project: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    priority: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    qaEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    queue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    start: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusStartTime: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusType: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    status: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    summary: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    tags: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Team: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    typeOf: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    version: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_testPlan: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_to_documentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_ssylkaNeTestPlan: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    ssylkaNeTestPlan: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    testPlan: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    to_documentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    unique: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    primaryKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    commentWithExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithoutExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastCommentUpdatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    originalEstimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    estimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatusLastAssignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolution: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    spent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    stand: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    storyPoints: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    votes: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    access: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    aliases: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bitrixTicketID: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockReason: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bugstage: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistDone: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistItems: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistTotal: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developmentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    emailTo: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    end: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendEnd: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendStart: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Frontend: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    receivedReplyFor: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    regress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    release: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheDesignReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheTesting: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Size: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    sla: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    userEmail: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

class Issues4(Base):
    __tablename__ = 'issues4'

    id: Mapped[Optional[str]] = mapped_column(String, primary_key=True)
    MRIntoDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    MRIntoMaster: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    dur_zhdetreliz: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_protestirovanoNaDevCustom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_gotovokrazrabotke: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closedDev: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_testing: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_zablokirovana: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_otmenena: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_novaja: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_inProgress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_beklog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_closed: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_open: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_dorabotka: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_vrazrabotke: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_oceredNaQa: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_backlog: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    dur_new: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    assignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    boards: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    components: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    createdBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    deadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    description: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    favorite: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    followers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    key: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    link: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    pendingReplyFrom: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    primaryKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    project: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    priority: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    qaEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    queue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    stand: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    start: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusStartTime: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    statusType: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    status: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    summary: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    tags: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Team: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    typeOf: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    updatedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    version: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_eeEngineer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    opisanieDlaRelizNouta: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    sprint: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    unique: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)

    commentWithExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    commentWithoutExternalMessageCount: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastCommentUpdatedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    originalEstimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    estimation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousStatusLastAssignee: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    parentStatus: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolution: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedAt: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    resolvedBy: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    spent: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    storyPoints: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    votes: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    access: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    aliases: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bitrixTicketID: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockKey: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    blockReason: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    bugstage: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistDone: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistItems: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    checklistTotal: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developer: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    developmentDeadline: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    emailTo: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    end: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendEnd: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendStart: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Frontend: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lastQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    previousQueue: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    receivedReplyFor: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    regress: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    release: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheDesignReview: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    returnsFromTheTesting: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    Size: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    sla: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    userEmail: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_frontendPresentation: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_lead: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    local_reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)
    reviewers: Mapped[Optional[str]] = mapped_column(String, nullable=True, default=None)