"""small fix

Revision ID: 1bb24cbfe1b6
Revises: 62dde7555ad7
Create Date: 2025-06-18 16:01:22.984263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb24cbfe1b6'
down_revision: Union[str, None] = '62dde7555ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dev_duration', 'returns_to_work_from_review')
    op.add_column('return_to_work_from_review', sa.Column('returns_to_work_from_design_review', sa.Integer(), nullable=False))
    op.drop_column('return_to_work_from_review', 'returns_to_work_from_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_to_work_from_review', sa.Column('returns_to_work_from_review', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('return_to_work_from_review', 'returns_to_work_from_design_review')
    op.add_column('dev_duration', sa.Column('returns_to_work_from_review', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
