"""added status duration for issue3, issue4

Revision ID: 580fcf0b5b7a
Revises: e04615821d69
Create Date: 2025-07-15 00:59:45.472203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580fcf0b5b7a'
down_revision: Union[str, None] = 'e04615821d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues3', sa.Column('dur_zakryta', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_otmenena', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_novaja', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_bagpodtverzhden', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_transferredtothedevelopers', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_acceptance', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_inProgress', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_vrazrabotke', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_backlog', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_dizajn', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_tpRndPoc', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_estNaDev', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_otklonen', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_new', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_testing', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_testplan', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_tpVRabote', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_needsProcessing', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_needsTZ', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_zhdetreliz', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_inReview', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_protestirovanoNaDevCustom', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_gotovokrazrabotke', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_closedDev', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_testing', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_zablokirovana', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_otmenena', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_novaja', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_inProgress', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_beklog', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_closed', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_open', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_dorabotka', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_vrazrabotke', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_oceredNaQa', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_backlog', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_new', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues4', 'dur_new')
    op.drop_column('issues4', 'dur_backlog')
    op.drop_column('issues4', 'dur_oceredNaQa')
    op.drop_column('issues4', 'dur_vrazrabotke')
    op.drop_column('issues4', 'dur_dorabotka')
    op.drop_column('issues4', 'dur_open')
    op.drop_column('issues4', 'dur_closed')
    op.drop_column('issues4', 'dur_beklog')
    op.drop_column('issues4', 'dur_inProgress')
    op.drop_column('issues4', 'dur_novaja')
    op.drop_column('issues4', 'dur_otmenena')
    op.drop_column('issues4', 'dur_zablokirovana')
    op.drop_column('issues4', 'dur_testing')
    op.drop_column('issues4', 'dur_closedDev')
    op.drop_column('issues4', 'dur_gotovokrazrabotke')
    op.drop_column('issues4', 'dur_protestirovanoNaDevCustom')
    op.drop_column('issues4', 'dur_inReview')
    op.drop_column('issues4', 'dur_zhdetreliz')
    op.drop_column('issues3', 'dur_needsTZ')
    op.drop_column('issues3', 'dur_needsProcessing')
    op.drop_column('issues3', 'dur_tpVRabote')
    op.drop_column('issues3', 'dur_testplan')
    op.drop_column('issues3', 'dur_testing')
    op.drop_column('issues3', 'dur_new')
    op.drop_column('issues3', 'dur_otklonen')
    op.drop_column('issues3', 'dur_estNaDev')
    op.drop_column('issues3', 'dur_tpRndPoc')
    op.drop_column('issues3', 'dur_dizajn')
    op.drop_column('issues3', 'dur_backlog')
    op.drop_column('issues3', 'dur_vrazrabotke')
    op.drop_column('issues3', 'dur_inProgress')
    op.drop_column('issues3', 'dur_acceptance')
    op.drop_column('issues3', 'dur_transferredtothedevelopers')
    op.drop_column('issues3', 'dur_bagpodtverzhden')
    op.drop_column('issues3', 'dur_novaja')
    op.drop_column('issues3', 'dur_otmenena')
    op.drop_column('issues3', 'dur_zakryta')
    # ### end Alembic commands ###
