"""added return_to_work_from_review and dev_duration

Revision ID: 62dde7555ad7
Revises: 119316391576
Create Date: 2025-06-18 15:45:48.265412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dde7555ad7'
down_revision: Union[str, None] = '119316391576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_duration',
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('parent_tag', sa.String(), nullable=False),
    sa.Column('returns_to_work_from_review', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('return_to_work_from_review',
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('returns_to_work_from_review', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('return_to_work_from_tests',
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('returns_to_work', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('return_to_work')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_to_work',
    sa.Column('queue', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('returns_to_work', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_table('return_to_work_from_tests')
    op.drop_table('return_to_work_from_review')
    op.drop_table('dev_duration')
    # ### end Alembic commands ###
