"""upgrade issue4

Revision ID: 6464a2c800cf
Revises: 9c5f7d098dac
Create Date: 2025-07-15 12:08:48.344610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6464a2c800cf'
down_revision: Union[str, None] = '9c5f7d098dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues4', sa.Column('dur_waitingForTheOtherTeam', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues4', 'dur_waitingForTheOtherTeam')
    # ### end Alembic commands ###
