"""added status duration for issue1

Revision ID: 6a83524777e8
Revises: 8b9269efa153
Create Date: 2025-07-15 00:40:54.682918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a83524777e8'
down_revision: Union[str, None] = '8b9269efa153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('dur_zakryta', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_cancelled', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_obrabotka', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_protestirovanoNaDevCustom', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_testing', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_zablokirovana', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_dizajnrevju', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_closedDev', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_inReview', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_closed', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_novaja', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_inProgress', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_proverkaPostanovsikom', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_beklog', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_tehniceskijProekt', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_oceredNaQa', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_backlog', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_closedProd', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues1', 'dur_closedProd')
    op.drop_column('issues1', 'dur_backlog')
    op.drop_column('issues1', 'dur_oceredNaQa')
    op.drop_column('issues1', 'dur_tehniceskijProekt')
    op.drop_column('issues1', 'dur_beklog')
    op.drop_column('issues1', 'dur_proverkaPostanovsikom')
    op.drop_column('issues1', 'dur_inProgress')
    op.drop_column('issues1', 'dur_novaja')
    op.drop_column('issues1', 'dur_closed')
    op.drop_column('issues1', 'dur_inReview')
    op.drop_column('issues1', 'dur_closedDev')
    op.drop_column('issues1', 'dur_dizajnrevju')
    op.drop_column('issues1', 'dur_zablokirovana')
    op.drop_column('issues1', 'dur_testing')
    op.drop_column('issues1', 'dur_protestirovanoNaDevCustom')
    op.drop_column('issues1', 'dur_obrabotka')
    op.drop_column('issues1', 'dur_cancelled')
    op.drop_column('issues1', 'dur_zakryta')
    # ### end Alembic commands ###
