"""upgrade issue1

Revision ID: 81818d65d9d9
Revises: fcf20b151eb0
Create Date: 2025-07-15 10:28:58.036937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81818d65d9d9'
down_revision: Union[str, None] = 'fcf20b151eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('dur_otklonen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues1', 'dur_otklonen')
    # ### end Alembic commands ###
