"""update isuue1

Revision ID: 81d0e795f373
Revises: 66ca5e50054d
Create Date: 2025-07-14 14:45:16.680557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d0e795f373'
down_revision: Union[str, None] = '66ca5e50054d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('Team', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('eeEngineer', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('local_eeEngineer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues1', 'local_eeEngineer')
    op.drop_column('issues1', 'eeEngineer')
    op.drop_column('issues1', 'Team')
    # ### end Alembic commands ###
