"""update isuue2

Revision ID: 8b9269efa153
Revises: 81d0e795f373
Create Date: 2025-07-14 14:47:55.291389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9269efa153'
down_revision: Union[str, None] = '81d0e795f373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues2', sa.Column('Team', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('eeEngineer', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('local_eeEngineer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues2', 'local_eeEngineer')
    op.drop_column('issues2', 'eeEngineer')
    op.drop_column('issues2', 'Team')

    # ### end Alembic commands ###
