"""upgrade issues

Revision ID: 9c5f7d098dac
Revises: 81818d65d9d9
Create Date: 2025-07-15 11:27:33.369543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5f7d098dac'
down_revision: Union[str, None] = '81818d65d9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('dur_open', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_waitingForTheOtherTeam', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_new', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('dur_approval', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_inReview', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_obrabotka', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_novaja', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_obrabotka', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_thebugislocalized', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_closed', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_closedDev', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('dur_open', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_obrabotka', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('dur_zakryta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues4', 'dur_zakryta')
    op.drop_column('issues4', 'dur_obrabotka')
    op.drop_column('issues3', 'dur_open')
    op.drop_column('issues3', 'dur_closedDev')
    op.drop_column('issues3', 'dur_closed')
    op.drop_column('issues3', 'dur_thebugislocalized')
    op.drop_column('issues3', 'dur_obrabotka')
    op.drop_column('issues2', 'dur_novaja')
    op.drop_column('issues2', 'dur_obrabotka')
    op.drop_column('issues2', 'dur_inReview')
    op.drop_column('issues1', 'dur_approval')
    op.drop_column('issues1', 'dur_new')
    op.drop_column('issues1', 'dur_waitingForTheOtherTeam')
    op.drop_column('issues1', 'dur_open')
    # ### end Alembic commands ###
