"""added returns columns

Revision ID: a58a1208badd
Revises: ae9423ccf828
Create Date: 2025-07-29 22:43:47.806234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58a1208badd'
down_revision: Union[str, None] = 'ae9423ccf828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('returns_to_work_from_design_review', sa.Integer(), nullable=True))
    op.add_column('issues1', sa.Column('returns_to_work_from_tests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues1', 'returns_to_work_from_tests')
    op.drop_column('issues1', 'returns_to_work_from_design_review')
    # ### end Alembic commands ###
