"""update isuue1 complete

Revision ID: d0b34e7bbaf5
Revises: d8d1b52b952e
Create Date: 2025-07-14 13:10:27.017702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b34e7bbaf5'
down_revision: Union[str, None] = 'd8d1b52b952e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues1',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('MRIntoDev', sa.String(), nullable=True),
    sa.Column('MRIntoMaster', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('boards', sa.String(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('favorite', sa.String(), nullable=True),
    sa.Column('followers', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('pendingReplyFrom', sa.String(), nullable=True),
    sa.Column('primaryKey', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('qaEngineer', sa.String(), nullable=True),
    sa.Column('queue', sa.String(), nullable=True),
    sa.Column('stand', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('statusStartTime', sa.String(), nullable=True),
    sa.Column('statusType', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('typeOf', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('updatedBy', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('commentWithExternalMessageCount', sa.String(), nullable=True),
    sa.Column('commentWithoutExternalMessageCount', sa.String(), nullable=True),
    sa.Column('lastCommentUpdatedAt', sa.String(), nullable=True),
    sa.Column('originalEstimation', sa.String(), nullable=True),
    sa.Column('estimation', sa.String(), nullable=True),
    sa.Column('previousStatus', sa.String(), nullable=True),
    sa.Column('previousStatusLastAssignee', sa.String(), nullable=True),
    sa.Column('parentDeadline', sa.String(), nullable=True),
    sa.Column('parentStatus', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('resolvedAt', sa.String(), nullable=True),
    sa.Column('resolvedBy', sa.String(), nullable=True),
    sa.Column('spent', sa.String(), nullable=True),
    sa.Column('storyPoints', sa.String(), nullable=True),
    sa.Column('votes', sa.String(), nullable=True),
    sa.Column('access', sa.String(), nullable=True),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('bitrixTicketID', sa.String(), nullable=True),
    sa.Column('blockKey', sa.String(), nullable=True),
    sa.Column('blockReason', sa.String(), nullable=True),
    sa.Column('bugstage', sa.String(), nullable=True),
    sa.Column('checklistDone', sa.String(), nullable=True),
    sa.Column('checklistItems', sa.String(), nullable=True),
    sa.Column('checklistTotal', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('developmentDeadline', sa.String(), nullable=True),
    sa.Column('emailTo', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('frontPresentation', sa.String(), nullable=True),
    sa.Column('frontendEnd', sa.String(), nullable=True),
    sa.Column('frontendStart', sa.String(), nullable=True),
    sa.Column('Frontend', sa.String(), nullable=True),
    sa.Column('lastQueue', sa.String(), nullable=True),
    sa.Column('previousQueue', sa.String(), nullable=True),
    sa.Column('receivedReplyFor', sa.String(), nullable=True),
    sa.Column('regress', sa.String(), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('returnsFromTheDesignReview', sa.String(), nullable=True),
    sa.Column('returnsFromTheTesting', sa.String(), nullable=True),
    sa.Column('Size', sa.String(), nullable=True),
    sa.Column('sla', sa.String(), nullable=True),
    sa.Column('userEmail', sa.String(), nullable=True),
    sa.Column('frontendPresentation', sa.String(), nullable=True),
    sa.Column('lead', sa.String(), nullable=True),
    sa.Column('local_frontendPresentation', sa.String(), nullable=True),
    sa.Column('local_lead', sa.String(), nullable=True),
    sa.Column('local_reviewers', sa.String(), nullable=True),
    sa.Column('reviewers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues1')
    # ### end Alembic commands ###
