"""added status duration for issue2

Revision ID: e04615821d69
Revises: 6a83524777e8
Create Date: 2025-07-15 00:51:05.558466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04615821d69'
down_revision: Union[str, None] = '6a83524777e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues2', sa.Column('dur_onHold', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_transferredtothedevelopers', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_zakryta', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_thebugislocalized', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_zhdetreliz', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_testing', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_closedDev', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_closed', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_inProgress', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_checkforProduction', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_needsProcessing', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_dubl', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_otklonen', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_bagpodtverzhden', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_backlog', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('dur_new', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues2', 'dur_new')
    op.drop_column('issues2', 'dur_backlog')
    op.drop_column('issues2', 'dur_bagpodtverzhden')
    op.drop_column('issues2', 'dur_otklonen')
    op.drop_column('issues2', 'dur_dubl')
    op.drop_column('issues2', 'dur_needsProcessing')
    op.drop_column('issues2', 'dur_checkforProduction')
    op.drop_column('issues2', 'dur_inProgress')
    op.drop_column('issues2', 'dur_closed')
    op.drop_column('issues2', 'dur_closedDev')
    op.drop_column('issues2', 'dur_testing')
    op.drop_column('issues2', 'dur_zhdetreliz')
    op.drop_column('issues2', 'dur_thebugislocalized')
    op.drop_column('issues2', 'dur_zakryta')
    op.drop_column('issues2', 'dur_transferredtothedevelopers')
    op.drop_column('issues2', 'dur_onHold')
    # ### end Alembic commands ###
