"""update isuue3 1/2

Revision ID: e51bb580dde2
Revises: 9408ca072fa4
Create Date: 2025-07-14 14:06:43.347102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51bb580dde2'
down_revision: Union[str, None] = '9408ca072fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues3',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MRIntoDev', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MRIntoMaster', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aliases', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bitrixTicketID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blockKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blockReason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('boards', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bugstage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checklistDone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checklistItems', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checklistTotal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commentWithExternalMessageCount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commentWithoutExternalMessageCount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('components', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developmentDeadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('eeEngineer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emailTo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estimation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('favorite', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frontPresentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frontendEnd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frontendStart', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Frontend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastCommentUpdatedAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastQueue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_eeEngineer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_testPlan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_to_documentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_ssylkaNeTestPlan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('originalEstimation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parentDeadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parentStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pendingReplyFrom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previousQueue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previousStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previousStatusLastAssignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primaryKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qaEngineer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receivedReplyFor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolvedAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolvedBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('returnsFromTheDesignReview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('returnsFromTheTesting', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sla', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('spent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('statusStartTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('statusType', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('storyPoints', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ssylkaNeTestPlan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('testPlan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_documentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('typeOf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unique', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updatedBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('userEmail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('votes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frontendPresentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_frontendPresentation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_lead', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_reviewers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('issues3_pkey'))
    )
    # ### end Alembic commands ###
