"""update project column

Revision ID: eb251a602773
Revises: a58a1208badd
Create Date: 2025-07-30 11:05:40.088781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb251a602773'
down_revision: Union[str, None] = 'a58a1208badd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues1', sa.Column('project_primary', sa.String(), nullable=True))
    op.add_column('issues1', sa.Column('project_secondary', sa.String(), nullable=True))
    op.drop_column('issues1', 'project')
    op.add_column('issues2', sa.Column('project_primary', sa.String(), nullable=True))
    op.add_column('issues2', sa.Column('project_secondary', sa.String(), nullable=True))
    op.drop_column('issues2', 'project')
    op.add_column('issues3', sa.Column('project_primary', sa.String(), nullable=True))
    op.add_column('issues3', sa.Column('project_secondary', sa.String(), nullable=True))
    op.drop_column('issues3', 'project')
    op.add_column('issues4', sa.Column('project_primary', sa.String(), nullable=True))
    op.add_column('issues4', sa.Column('project_secondary', sa.String(), nullable=True))
    op.drop_column('issues4', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues4', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('issues4', 'project_secondary')
    op.drop_column('issues4', 'project_primary')
    op.add_column('issues3', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('issues3', 'project_secondary')
    op.drop_column('issues3', 'project_primary')
    op.add_column('issues2', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('issues2', 'project_secondary')
    op.drop_column('issues2', 'project_primary')
    op.add_column('issues1', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('issues1', 'project_secondary')
    op.drop_column('issues1', 'project_primary')
    # ### end Alembic commands ###
