"""update issue3

Revision ID: fcf20b151eb0
Revises: 580fcf0b5b7a
Create Date: 2025-07-15 01:02:05.341373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf20b151eb0'
down_revision: Union[str, None] = '580fcf0b5b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues3', sa.Column('dur_gotovokrazrabotke', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues3', 'dur_gotovokrazrabotke')
    # ### end Alembic commands ###
